# Generated by Django 4.2.7 on 2026-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='sgPromocao',
        ),
        migrations.AddField(
            model_name='produto',
            name='msgPromocao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
