# Generated by Django 4.2.7 on 2026-05-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_produto_sgpromocao_produto_msgpromocao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='abricante',
            new_name='fabricante',
        ),
    ]
